### PR TITLE
GetList needs to respond differently for Relations and Collections

### PR DESCRIPTION
**Pull request by bloveless**

### CODE REVIEW

**Comment by bloveless** [comment]
Should have tested a little more. It was working for the create, but not for the edit.

**Comment by RyanThompson** [comment]
Value should aways be instance of relation?

**Comment by bloveless** [comment]
The error that I got was that the function ->select doesn't exist on edit. Removing it fixed it. When I dumped $value it was an EntryCollection on edit, and a BelongsToMany on create. Maybe there is a deeper issue that I'm not seeing.

**Comment by RyanThompson** [comment]
Hmm.. Ya that should always be the relation..

**Comment by bloveless** [comment]
Fixed! Nicely done @RyanThompson

**Pull request closed without merging**
